# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb-auth-slice-password}
  s.version = "1.2.0.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman"]
  s.date = %q{2011-05-16}
  s.description = %q{Merb Slice with password UI support}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "TODO",
    "app/controllers/application.rb",
    "app/controllers/exceptions.rb",
    "app/controllers/sessions.rb",
    "app/helpers/application_helper.rb",
    "app/views/exceptions/unauthenticated.html.erb",
    "app/views/layout/merb-auth-slice-password.html.erb",
    "config/init.rb",
    "lib/merb-auth-slice-password.rb",
    "lib/merb-auth-slice-password/merbtasks.rb",
    "lib/merb-auth-slice-password/slicetasks.rb",
    "lib/merb-auth-slice-password/spectasks.rb",
    "lib/merb-auth-slice-password/version.rb",
    "public/javascripts/master.js",
    "public/stylesheets/master.css",
    "spec/merb-auth-slice-password_spec.rb",
    "spec/spec_helper.rb",
    "stubs/app/controllers/sessions.rb"
  ]
  s.homepage = %q{http://merbivore.com/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Merb Slice that provides UI for password strategy of merb-auth.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-slices>, ["~> 1.2.0.pre"])
      s.add_runtime_dependency(%q<merb-auth-core>, ["~> 1.2.0.pre1"])
      s.add_runtime_dependency(%q<merb-auth-more>, ["~> 1.2.0.pre1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<merb-slices>, ["~> 1.2.0.pre"])
      s.add_dependency(%q<merb-auth-core>, ["~> 1.2.0.pre1"])
      s.add_dependency(%q<merb-auth-more>, ["~> 1.2.0.pre1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<merb-slices>, ["~> 1.2.0.pre"])
    s.add_dependency(%q<merb-auth-core>, ["~> 1.2.0.pre1"])
    s.add_dependency(%q<merb-auth-more>, ["~> 1.2.0.pre1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

