require 'rubygems'
require 'rake'

# Load merb-slices, merb-auth-core and merb-auth-more version information
require File.expand_path('../../../merb/merb-slices/lib/merb-slices/version', __FILE__)
require File.expand_path('../../merb-auth-core/lib/merb-auth-core/version', __FILE__)
require File.expand_path('../../merb-auth-more/lib/merb-auth-more/version', __FILE__)

# Load this library's version information
require File.expand_path('../lib/merb-auth-slice-password/version', __FILE__)

begin

  gem 'jeweler', '~> 1.4'
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = Merb::Auth::More::VERSION.dup

    gemspec.name        = "merb-auth-slice-password"
    gemspec.description = "Merb Slice with password UI support"
    gemspec.summary     = "Merb Slice that provides UI for password strategy of merb-auth."

    gemspec.authors     = [ "Daniel Neighman" ]
    gemspec.email       = "has.sox@gmail.com"
    gemspec.homepage    = "http://merbivore.com/"

    gemspec.files       = %w(LICENSE Rakefile README.textile TODO) + Dir[
      '{app,config,lib,public,spec,stubs}/**/*'
    ]

    # Runtime dependencies
    gemspec.add_dependency 'merb-slices',    "~> #{Merb::Slices::VERSION}"
    gemspec.add_dependency 'merb-auth-core', "~> #{Merb::Auth::Core::VERSION}"
    gemspec.add_dependency 'merb-auth-more', "~> #{Merb::Auth::More::VERSION}"

    # Development dependencies              
    gemspec.add_development_dependency 'rspec', ">= 1.2.9"

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.spec_opts << '--options' << 'spec/spec.opts' if File.exists?('spec/spec.opts')
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

Spec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end
