require 'rubygems'
require 'rake'

# Assume a typical dev checkout to fetch the current merb-core version
require File.expand_path('../../../merb/merb-core/lib/merb-core/version', __FILE__)
require File.expand_path('../../merb-auth-core/lib/merb-auth-core/version', __FILE__)

# Load this library's version information
require File.expand_path('../lib/merb-auth/version', __FILE__)

begin

  gem 'jeweler', '~> 1.4'
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = Merb::Auth::VERSION.dup

    gemspec.name        = "merb-auth"
    gemspec.description = "Merb plugin that provides authentication support"
    gemspec.summary     = "The official authentication plugin for merb.  Setup for the default stack"

    gemspec.authors     = [ "Daniel Neighman" ]
    gemspec.email       = "has.sox@gmail.com"
    gemspec.homepage    = "http://merbivore.com/"

    # Needs to be listed explicitly because jeweler
    # otherwise thinks that everything inside the
    # merb-auth repo belongs to the merb-auth meta gem
    gemspec.files = [
      'LICENSE',
      'Rakefile',
      'README.textile',
      'TODO',
      'lib/merb-auth.rb',
      'lib/merb-auth/version.rb'
    ]

    # Runtime dependencies
    gemspec.add_dependency 'merb-core',                '~> 1.2.0.pre'
    gemspec.add_dependency 'merb-auth-core',           "~> #{Merb::Auth::Core::VERSION}"
    gemspec.add_dependency 'merb-auth-more',           "~> #{Merb::Auth::Core::VERSION}"
    gemspec.add_dependency 'merb-auth-slice-password', "~> #{Merb::Auth::Core::VERSION}"

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end
