require 'rubygems'
require 'rake'

# Assume a typical dev checkout to fetch the current merb-core version
require File.expand_path('../../../merb/merb-core/lib/merb-core/version', __FILE__)

# Load this library's version information
require File.expand_path('../lib/merb-auth-core/version', __FILE__)

begin

  gem 'jeweler', '~> 1.4'
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = Merb::Auth::Core::VERSION.dup

    gemspec.name        = "merb-auth-core"
    gemspec.description = "An Authentication framework for Merb"
    gemspec.summary     = "Merb plugin that provides basic authentication support"

    gemspec.authors     = [ "Adam French", "Daniel Neighman" ]
    gemspec.email       = "has.sox@gmail.com"
    gemspec.homepage    = "http://merbivore.com/"

    gemspec.files       = %w(LICENSE Rakefile README.textile TODO) + Dir['{lib,spec}/**/*']

    # Runtime dependencies
    gemspec.add_dependency 'merb-core', '~> 1.2.0.pre'

    # Development dependencies
    gemspec.add_development_dependency 'rspec', ">= 2.5"

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = "spec/**/*_spec.rb"
  spec.fail_on_error = false
end

RSpec::Core::RakeTask.new(:rcov) do |spec|
  spec.pattern = "spec/**/*_spec.rb"
  spec.fail_on_error = false
  spec.rcov = true
end
