require 'rubygems'
require 'rake'

# Load merb-auth-core version information
require File.expand_path('../../merb-auth-core/lib/merb-auth-core/version', __FILE__)

# Load this library's version information
require File.expand_path('../lib/merb-auth-more/version', __FILE__)

begin

  gem 'jeweler', '~> 1.4'
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = Merb::Auth::More::VERSION.dup

    gemspec.name        = "merb-auth-more"
    gemspec.description = "Addons for merb-auth-core"
    gemspec.summary     = "Additional resources for use with the merb-auth-core authentication framework."

    gemspec.authors     = [ "Daniel Neighman" ]
    gemspec.email       = "has.sox@gmail.com"
    gemspec.homepage    = "http://merbivore.com/"

    gemspec.files       = %w(LICENSE Rakefile README.textile TODO) + Dir['{lib,spec}/**/*']

    # Runtime dependencies
    gemspec.add_dependency 'merb-auth-core', "~> #{Merb::Auth::Core::VERSION}"

    # Development dependencies
    gemspec.add_development_dependency 'rspec', ">= 2.5"

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = "spec/**/*_spec.rb"
  spec.fail_on_error = false
end

RSpec::Core::RakeTask.new(:rcov) do |spec|
  spec.pattern = "spec/**/*_spec.rb"
  spec.fail_on_error = false
  spec.rcov = true
end
